### ISSUE TITLE
При проверке наличия существующей игры в каталоге возвращает false

### ISSUE THREAD

**Issue by DesertScream** [Kuzzzya/TeamProject#1]
# Описание

При проверке метода `publishGame` тестом с существующей в каталоге игрой, выдает false, а должно true.

# Локация дефекта

https://github.com/Kuzzzya/TeamProject/blob/6607b91eb53bf7c04c3ae4f27edb022d2e99f0aa/src/main/java/ru/netology/GameStore.java#L32

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Kuzzzya/TeamProject/blob/6607b91eb53bf7c04c3ae4f27edb022d2e99f0aa/src/main/java/ru/netology/GameStore.java) в IDEA
2. Создать объект из GameStore
3. Создать объект игры вызовом метода publishGame с параметрами "Нетология Баттл Онлайн" и "Аркады"
4.  Проверить методом assertTrue, что передаваемое выражение методом containsGame истинно
5. [Ссылка](https://github.com/Kuzzzya/TeamProject/blob/6607b91eb53bf7c04c3ae4f27edb022d2e99f0aa/src/test/java/ru/netology/GameStoreTest.java#L8) на готовый автотест

*Ожидаемый результат:* true
*Фактический результат:* false

# Скриншот
![image](https://user-images.githubusercontent.com/94640822/162514021-29179a71-28fa-4577-b4f5-317091a15d97.png)
![image](https://user-images.githubusercontent.com/94640822/162513568-8a883dbe-efc8-4b48-bc88-7700b130e1dc.png)

# Окружение
* **Операционная система:** Windows 10 Версия 20H2
* **IDE:** IntelliJ IDEA 2021.3.2 (Community Edition)
* **Java:** OpenJDK 11 Eclipse Temurin version 11.0.13

**Comment by Kuzzzya** [comment]
commite 06054c9e152584268ab7f8015c0f42f9bba16a8d repair
CLOSED
