### ISSUE TITLE
Не суммируется новое проигранное время со старым 

### ISSUE THREAD

**Issue by DesertScream** [Kuzzzya/TeamProject#2]
# Описание

При добавлении нового проигранного времени методом addPlayTime в тесте ShouldGetMostPlayer к предыдущему времени игрока в игре не прибавляется новое время

# Локация дефекта

https://github.com/Kuzzzya/TeamProject/blob/45cbb0fcec184b01fb9feb48f584ca8700d0bcc8/src/main/java/ru/netology/GameStore.java#L46

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Kuzzzya/TeamProject/blob/6607b91eb53bf7c04c3ae4f27edb022d2e99f0aa/src/main/java/ru/netology/GameStore.java) в IDEA
2. Создать объект из GameStore
3. Добавить игроков с проигранным временем с помощью метода addPlayTime (игрок 1 - 10 часов, игрок 1 - 30 часов, игрок 2 -30 часов)
4. Проверить, что через метод getMostPlayer возвращается имя игрока, который играл больше всего времени
5. [Ссылка](https://github.com/Kuzzzya/TeamProject/blob/45cbb0fcec184b01fb9feb48f584ca8700d0bcc8/src/test/java/ru/netology/GameStoreTest.java#L44) на готовый тест 

*Ожидаемый результат:* 2
*Фактический результат:* 1

# Скриншот
![image](https://user-images.githubusercontent.com/94640822/162580937-bb4766fa-7926-4764-b0d4-2ecdae454f6e.png)
![image](https://user-images.githubusercontent.com/94640822/162580952-1b8ec435-81a9-4564-a265-ebf59f921362.png)

# Окружение
* **Операционная система:** Windows 10 Версия 20H2
* **IDE:** IntelliJ IDEA 2021.3.2 (Community Edition)
* **Java:** OpenJDK 11 Eclipse Temurin version 11.0.13

**Comment by Kuzzzya** [comment]
commit dcfa3e076e8de7ed4506927d10c2b37f2fcb7cf5 repair method addPlayedTime
CLOSED
